import smtplib
from email.mime.text import MIMEText

def send_email_alert(signal, stock, to_email):
    from_email = "aaradhanay8@gmail.com"
    password = "hqgfyvkgbznqkwls"   # Your app password

    subject = f"Stock Alert: {stock}"
    body = f"""
📊 AI Trading Alert

Stock: {stock}
Signal: {signal}

👉 Action: Consider trading this stock

Generated by AI Trading System
"""

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = from_email
    msg["To"] = to_email

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(from_email, password)
        server.send_message(msg)
        server.quit()
        print("✅ Email sent successfully!")
    except Exception as e:
        print("❌ Error:", e)